schema_version: 2
network: preprod
contract_slug: cip-68-444-config
assigned_handles:
  settings:
    - mint_config_444
  scripts: []
ignored_settings: []
settings:
  type: cip_68_444_config
  values:
    mint_config_444:
      fee_address: addr_test1vp0kpndjq9lycyx867fd78xflwnngg0tre2y0xl4mx86mzqp79y5w
      fee_schedule:
        - [0, 0]
        - [10000000, 1000000]
        - [35000000, 3000000]
