name = "koralabs/cip-68-444-minting"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'koralabs/cip-68-444-minting'"

[repository]
user = "koralabs"
project = "cip-68-444-minting"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "v2.1.0"
source = "github"

[config]
