schema_version: 2
network: preview
contract_slug: cip-68-444-config
assigned_handles:
  settings:
    - mint_config_444
  scripts: []
ignored_settings: []
settings:
  type: cip_68_444_config
  values:
    mint_config_444:
      fee_address: addr_test1xqv4hh3aat9kzwm7n6mzszc5md8r20j8t6tdr8el0f0z6eset00rm6ktvyaha84k9q93fk6wx5lywh5k6x0n77j794nqp4vpze
      fee_schedule:
        - [0, 0]
        - [11000000, 2000000]
        - [35000000, 3000000]
